---

- name: Create an instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volumes }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instance
  
- debug:
    msg: "Instance {{ item.openstack.name }} has been created. Ip address is {{ item.openstack.public_v4 }}."
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- debug: var=inventory_hostname
- debug: var=ansible_hostname

- name: Wait for connection
  wait_for:
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
    msg: "port 22 is not listening"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined
  
- name: Add host to groups
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: COMP90024
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined
  
- name: Add host to web
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: WEB
  loop: '{{ os_instance.results }}'
  when: item.openstack.name == web_instance_name
  
- name: Add host to db
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: DB
  loop: '{{ os_instance.results }}'
  when: item.openstack.name == db_instance_name
  