
availability_zone: melbourne-qh2-uom

volumes:
  - vol_name: web-vol-1
    vol_size: 10
  - vol_name: db-vol-1
    vol_size: 50

security_groups:
  - name: ssh
    description: "security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

instances:
  - name: webserver
    volumes: ['web-vol-1']
  - name: dbserver
    volumes: ['db-vol-1']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: Xianwei Gao
instance_flavor: uom.mse.2c9g