---
- name: Gather facts of remote host
  setup:
    gather_subset: all

- name: copy http-proxy file in etc/environment
  become: yes
  template:
    src: /etc/environment
    dest: /etc/environment
    mode: '0666'

- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: ['apt-transport-https', 'build-essential', 'ca-certificates']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  tags: always
  become: yes
  pip:
    name: ['pip']
    state: latest