---

- name: Create volumn snapshot
  os_volumn_snapshot:
    state: present
    volumn: '{{ item.vol_name }}'
    display_name: "{{ item.vol_name }}-{{ loopup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone }}'
  loop: '{{ volumns }}'